services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fxsignal_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fxsignal_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://49.212.186.28:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: