services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fxsignal_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data: